[package]
name = "open3d-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
autocxx = "0.24"
clap = { version = "4.1.6", features = ["derive"] }

[build-dependencies]
cxx-build = "1.0"
autocxx-build = "0.24"
miette = { version = "5", features = ["fancy"] }
