[package]
name = "open3d-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
autocxx = "0.24"

[build-dependencies]
cxx-build = "1.0"
autocxx-build = "0.23"
miette = { version = "5", features = ["fancy"] }